// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protocol/game.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_Ping) Reset() {
	*x = CS_Ping{}
	mi := &file_protocol_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Ping) ProtoMessage() {}

func (x *CS_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Ping.ProtoReflect.Descriptor instead.
func (*CS_Ping) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{0}
}

func (x *CS_Ping) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type SC_Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_Ping) Reset() {
	*x = SC_Ping{}
	mi := &file_protocol_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_Ping) ProtoMessage() {}

func (x *SC_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_Ping.ProtoReflect.Descriptor instead.
func (*SC_Ping) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{1}
}

func (x *SC_Ping) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_protocol_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{2}
}

func (x *Vector2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type CS_Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     *Vector2               `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_Move) Reset() {
	*x = CS_Move{}
	mi := &file_protocol_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_Move) ProtoMessage() {}

func (x *CS_Move) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_Move.ProtoReflect.Descriptor instead.
func (*CS_Move) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{3}
}

func (x *CS_Move) GetDirection() *Vector2 {
	if x != nil {
		return x.Direction
	}
	return nil
}

var File_protocol_game_proto protoreflect.FileDescriptor

const file_protocol_game_proto_rawDesc = "" +
	"\n" +
	"\x13protocol/game.proto\x12\bprotocol\"\x1d\n" +
	"\aCS_Ping\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"\x1d\n" +
	"\aSC_Ping\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\":\n" +
	"\aCS_Move\x12/\n" +
	"\tdirection\x18\x01 \x01(\v2\x11.protocol.Vector2R\tdirectionB\x16Z\x14game-server/protocolb\x06proto3"

var (
	file_protocol_game_proto_rawDescOnce sync.Once
	file_protocol_game_proto_rawDescData []byte
)

func file_protocol_game_proto_rawDescGZIP() []byte {
	file_protocol_game_proto_rawDescOnce.Do(func() {
		file_protocol_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_game_proto_rawDesc), len(file_protocol_game_proto_rawDesc)))
	})
	return file_protocol_game_proto_rawDescData
}

var file_protocol_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocol_game_proto_goTypes = []any{
	(*CS_Ping)(nil), // 0: protocol.CS_Ping
	(*SC_Ping)(nil), // 1: protocol.SC_Ping
	(*Vector2)(nil), // 2: protocol.Vector2
	(*CS_Move)(nil), // 3: protocol.CS_Move
}
var file_protocol_game_proto_depIdxs = []int32{
	2, // 0: protocol.CS_Move.direction:type_name -> protocol.Vector2
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocol_game_proto_init() }
func file_protocol_game_proto_init() {
	if File_protocol_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_game_proto_rawDesc), len(file_protocol_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_game_proto_goTypes,
		DependencyIndexes: file_protocol_game_proto_depIdxs,
		MessageInfos:      file_protocol_game_proto_msgTypes,
	}.Build()
	File_protocol_game_proto = out.File
	file_protocol_game_proto_goTypes = nil
	file_protocol_game_proto_depIdxs = nil
}
